# Generated by Django 3.0.7 on 2020-07-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('keyword', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
